name = "PickAssets"
uuid = "638530b6-8ef8-48c6-af00-01fe61e90122"
authors = ["Shayan <sh0davoodi@gmail.com>"]
version = "0.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
Dates = "1.11.0"
julia = "1.11"
